quotes = [
    "The best way to predict the future is to invent it. – Alan Kay",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "In order to be irreplaceable, one must always be different. – Coco Chanel",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. – Edsger Dijkstra",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "First, solve the problem. Then, write the code. – John Johnson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Debugging becomes significantly easier if you first admit that you are the problem. – William Laeder",
    "Real programmers don’t write specs. Users should consider themselves lucky to get any documentation at all. – Tom Van Vleck",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Deleted code is debugged code. – Jeff Sickel",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Deleted code is debugged code. – Jeff Sickel",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Deleted code is debugged code. – Jeff Sickel",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. – Edsger Dijkstra",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Deleted code is debugged code. – Jeff Sickel",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Deleted code is debugged code. – Jeff Sickel",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Deleted code is debugged code. – Jeff Sickel",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Deleted code is debugged code. – Jeff Sickel",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Make it work, make it right, make it fast. – Kent Beck",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "First, solve the problem. Then, write the code. – John Johnson",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "First, solve the problem. Then, write the code. – John Johnson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "The best way to predict the future is to invent it. – Alan Kay",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "First, solve the problem. Then, write the code. – John Johnson",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Deleted code is debugged code. – Jeff Sickel",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Deleted code is debugged code. – Jeff Sickel",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Fix the cause, not the symptom. – Steve Maguire",
    "First, solve the problem. Then, write the code. – John Johnson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Debugging becomes significantly easier if you first admit that you are the problem. – William Laeder",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Deleted code is debugged code. – Jeff Sickel",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Debugging becomes significantly easier if you first admit that you are the problem. – William Laeder",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Deleted code is debugged code. – Jeff Sickel",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Deleted code is debugged code. – Jeff Sickel",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "First, solve the problem. Then, write the code. – John Johnson",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Deleted code is debugged code. – Jeff Sickel",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Deleted code is debugged code. – Jeff Sickel",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Fix the cause, not the symptom. – Steve Maguire",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Deleted code is debugged code. – Jeff Sickel",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Deleted code is debugged code. – Jeff Sickel",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Make it work, make it right, make it fast. – Kent Beck",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Deleted code is debugged code. – Jeff Sickel",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Deleted code is debugged code. – Jeff Sickel",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Deleted code is debugged code. – Jeff Sickel",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Deleted code is debugged code. – Jeff Sickel",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "The function of good software is to make the complex appear to be simple. – Grady Booch",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "First, solve the problem. Then, write the code. – John Johnson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programming is the art of algorithm design and the craft of debugging errant code. – Ellen Ullman",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "Deleted code is debugged code. – Jeff Sickel",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Fix the cause, not the symptom. – Steve Maguire",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Programming can be fun, and so can cryptography; however, they should not be combined. – Kreitzberg & Shneiderman",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. – John Romero",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Deleted code is debugged code. – Jeff Sickel",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "Deleted code is debugged code. – Jeff Sickel",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Deleted code is debugged code. – Jeff Sickel",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Code is like a love letter: it’s better when it’s elegant. – Unknown",
    "A good programmer is someone who looks both ways before crossing a one-way street. – Doug Linder",
    "Deleted code is debugged code. – Jeff Sickel",
    "The computer was born to solve problems that did not exist before. – Bill Gates",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "Deleted code is debugged code. – Jeff Sickel",
    "Optimism is an occupational hazard of programming: feedback is the treatment. – Kent Beck",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "There are two ways to write error-free programs; only the third one works. – Alan J. Perlis",
    "Before software can be reusable it first has to be usable. – Ralph Johnson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. – Alan Perlis",
    "Deleted code is debugged code. – Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. – Bill Gates",
    "Testing leads to failure, and failure leads to understanding. – Burt Rutan",
    "The best error message is the one that never shows up. – Thomas Fuchs",
    "Good code is its own best documentation. – Steve McConnell",
    "It's not a bug – it's an undocumented feature. – Anonymous",
    "Without requirements or design, programming is the art of adding bugs to an empty text file. – Louis Srygley",
    "Code never lies, comments sometimes do. – Ron Jeffries",
    "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away. – Antoine de Saint-Exupéry",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. – Anonymous",
    "Software is a great combination between artistry and engineering. – Bill Gates",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. – Patrick McKenzie",
    "The most disastrous thing that you can ever learn is your first programming language. – Alan Kay",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. – John Woods",
    "The trouble with programmers is that you can never tell what a programmer is doing until it's too late. – Seymour Cray",
    "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code. – Dan Salomon",
    "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning. – Rick Cook",
    "The bearing of a child takes nine months, no matter how many women are assigned. – Frederick P. Brooks Jr.",
    "Good design adds value faster than it adds cost. – Thomas C. Gale",
    "The cheapest, fastest, and most reliable components are those that aren't there. – Gordon Bell",
    "Documentation is a love letter that you write to your future self. – Damian Conway",
    "Learning to write programs stretches your mind, and helps you think better, creates a way of thinking about things that I think is helpful in all domains. – Bill Gates",
    "Low-level programming is good for the programmer's soul. – John Carmack",
    "It's harder to read code than to write it. – Joel Spolsky",
    "The most important property of a program is whether it accomplishes the intention of its user. – C.A.R. Hoare",
]
