name: Update README Quote

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run update_quote.py
        run: python update_quote.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
        run: |
          git config --global user.name "krikera"  
          git config --global user.email "prafulrai522@gmail.com"
          
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "🤖 Update daily inspirational quote"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
