name: Update README Quote

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run update_quote.py
        run: python update_quote.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT instead of default token
        run: |
          git config --global user.name "YourGitHubUsername"  # Replace with your username
          git config --global user.email "your-email@example.com"  # Use the email linked to GitHub

          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "🤖 Update daily inspirational quote"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
